name: pol_chi
description: بازی پول‌چی - الیگودرز ۱۴۰۵
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/characters/
    - assets/images/businesses/
    - assets/images/background/
